version: '3'
services:

  keycloak-db:
    image: postgres:9.6
    networks:
      - keycloak-net
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres

  keycloak:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: keycloak
    restart: always
    ports:
      - "8180:8180"
    volumes:
      - ./realm.json:/tmp/realm.json
    command: [
        "-Djboss.http.port=8180",
        "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ]
    depends_on:
      - keycloak-db
    networks:
      - keycloak-net
    environment:
      KEYCLOAK_IMPORT: ./tmp/realm.json

      DB_VENDOR:   POSTGRES
      DB_ADDR:     keycloak-db
      DB_PORT:     5432

      DB_DATABASE: keycloak
      DB_SCHEMA: public

      DB_USER:     keycloak
      DB_PASSWORD: password

      KEYCLOAK_USER:     admin
      KEYCLOAK_PASSWORD: admin

      KEYCLOAK_LOGLEVEL: INFO


networks:
  keycloak-net: